[package]
name = "lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
proptest = "1.4.0"

[dependencies]
argon2 = "0.5.2"
derive_more = "0.99.17"
jsonwebtoken = "9.2.0"
serde_json = "1.0.111"

[dependencies.rand_core]
version = "0.6.4"
features = ["getrandom"]

[dependencies.uuid]
version = "1.6.1"
features = ["serde", "v4"]

[dependencies.chrono]
version = "0.4.31"
features = ["serde"]

[dependencies.serde]
version = "1.0.194"
features = ["derive"]

[dependencies.utoipa]
version = "4.2.0"
features = ["chrono", "uuid", "actix_extras"]
optional = true

[dependencies.sqlx]
version = "0.7.3"
features = ["tls-native-tls", "runtime-async-std", "postgres", "chrono", "uuid"]
optional = true

[features]
default = []
full = ["dep:utoipa", "dep:sqlx"]
